### ISSUE TITLE
리플레이 관련

### ISSUE THREAD

**Issue by Luigi38** [MineEric64/IGReinforced#2]
Replay를 킨지 30초가 지나면 리플레이가 저장이 되지 않음

**Comment by Luigi38** [comment]
Replay를 끄면 오류가 나면서 튕김

**Comment by MineEric64** [comment]
`ClearAllBuffer()` 사용 시 `_flow.Reset()` 써야함.
안그러면 `Elapsed`가 `ReplayLength`를 계속 넘겨서 하이라이트가 누적이 되지 않음.

**Comment by MineEric64** [comment]
Accumulating partital data not supported
